/*
 * SPDX-FileCopyrightText: Copyright 2020-2026 OpenRTX Contributors
 * 
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef ENGLISHSTRINGS_H
#define ENGLISHSTRINGS_H

#include "ui/ui_strings.h"

const stringsTable_t englishStrings =
{
    .languageName      = "English",
    .off               = "OFF",
    .on                = "ON",
    .banks             = "Banks",
    .channels          = "Channels",
    .contacts          = "Contacts",
    .gps               = "GPS",
    .settings          = "Settings",
    .backupAndRestore  = "Backup & Restore",
    .info              = "Info",
    .about             = "About",
    .display           = "Display",
    .timeAndDate       = "Time & Date",
    .fm                = "FM",
    .m17               = "M17",
    .dmr               = "DMR",
    .defaultSettings   = "Default Settings",
    .brightness        = "Brightness",
    .contrast          = "Contrast",
    .timer             = "Timer",
    .gpsEnabled        = "GPS Enabled",
    .gpsSetTime        = "GPS Set Time",
    .UTCTimeZone       = "UTC Timezone",
    .voice             = "Voice",
    .level             = "Level",
    .phonetic          = "Phonetic",
    .beep              = "Beep",
    .backup            = "Backup",
    .restore           = "Restore",
    .batteryVoltage    = "Bat. Voltage",
    .batteryCharge     = "Bat. Charge",
    .RSSI              = "RSSI",
    .model             = "Model",
    .band              = "Band",
    .VHF               = "VHF",
    .UHF               = "UHF",
    .LCDType           = "LCD Type",
    .Niccolo           = "Niccolo' IU2KIN",
    .Silvano           = "Silvano IU2KWO",
    .Federico          = "Federico IU2NUO",
    .Fred              = "Fred IU2NRO",
    .Joseph            = "Joseph VK7JS",
    .allChannels       = "All channels",
    .menu              = "Menu",
    .gpsOff            = "GPS OFF",
    .noFix             = "No Fix",
    .fixLost           = "Fix Lost",
    .error             = "ERROR",
    .flashBackup       = "Flash Backup",
    .connectToRTXTool  = "Connect to RTXTool",
    .toBackupFlashAnd  = "to backup flash and",
    .pressPTTToStart   = "press PTT to start.",
    .flashRestore      = "Flash Restore",
    .toRestoreFlashAnd = "to restore flash and",
    .openRTX           = "OpenRTX",
    .gpsSettings       = "GPS Settings",
    .m17settings       = "M17 Settings",
    .callsign          = "Callsign",
    .resetToDefaults   = "Reset to Defaults",
    .toReset           = "To reset:",
    .pressEnterTwice   = "Press Enter twice",
    .macroMenu         = "Macro Menu",
    .forEmergencyUse   = "For emergency use",
    .pressAnyButton    = "press any button.",
    .accessibility     = "Accessibility",
    .usedHeap          = "Used heap",
    .broadcast         = "ALL",
    .radioSettings     = "Radio Settings",
    .offset            = "Offset",
    .macroLatching     = "Macro Latch",
    .noGps             = "No GPS",
    .batteryIcon       = "Battery Icon",
    .CTCSSTone         = "CTCSS Tone",
    .CTCSSEn           = "CTCSS En.",
    .Encode            = "Encode",
    .Decode            = "Decode",
    .Both              = "Both",
    .None              = "None",
    .direction         = "Direction",
    .step              = "Step",
    .radio             = "Radio",
    .CAN               = "CAN",
    .canRxCheck        = "CAN RX Check",
};
#endif  // ENGLISHSTRINGS_H
