/*
 * SPDX-FileCopyrightText: Copyright 2020-2026 OpenRTX Contributors
 * 
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef SPANISHSTRINGS_H
#define SPANISHSTRINGS_H

#include "ui/ui_strings.h"

const stringsTable_t spanishStrings =
{
    .languageName      = "Español",
    .off               = "Apagado",
    .on                = "Encendido",
    .banks             = "Banks",
    .channels          = "Canales",
    .contacts          = "Contactos",
    .gps               = "GPS",
    .settings          = "Ajustes",
    .backupAndRestore  = "Backup & Restaurar",
    .info              = "Info",
    .about             = "Acerca de",
    .display           = "Display",
    .timeAndDate       = "Fecha & Hora",
    .fm                = "FM",
    .m17               = "M17",
    .dmr               = "DMR",
    .defaultSettings   = "Ajustes de fábrica",
    .brightness        = "Brillo",
    .contrast          = "Contraste",
    .timer             = "Cronómetro",
    .gpsEnabled        = "GPS habilitado",
    .gpsSetTime        = "GPS Ajustar hora",
    .UTCTimeZone       = "Zona Horaria UTC",
    .voice             = "Voz",
    .level             = "Nivel",
    .phonetic          = "Fonético",
    .beep              = "Bip",
    .backup            = "Backup",
    .restore           = "Restarurar",
    .batteryVoltage    = "Voltage Bat.",
    .batteryCharge     = "Carga Bat.",
    .RSSI              = "RSSI",
    .model             = "Modelo",
    .band              = "Banda",
    .VHF               = "VHF",
    .UHF               = "UHF",
    .LCDType           = "Tipo de LCD",
    .Niccolo           = "Niccolo' IU2KIN",
    .Silvano           = "Silvano IU2KWO",
    .Federico          = "Federico IU2NUO",
    .Fred              = "Fred IU2NRO",
    .Joseph            = "Joseph VK7JS",
    .allChannels       = "Todos los canales",
    .menu              = "Menu",
    .gpsOff            = "GPS Apagado",
    .noFix             = "Sin posición",
    .fixLost           = "Posición perdida",
    .error             = "ERROR",
    .flashBackup       = "Guardar Backup",
    .connectToRTXTool  = "Conectar con RTXTool",
    .toBackupFlashAnd  = "guardar flash y",
    .pressPTTToStart   = "Apretar PTT para iniciar",
    .flashRestore      = "Flash restore",
    .toRestoreFlashAnd = "to restore flash and",
    .openRTX           = "OpenRTX",
    .gpsSettings       = "Ajustes de GPS",
    .m17settings       = "Ajustes de M17",
    .callsign          = "Licencia",
    .resetToDefaults   = "Reseatear a fábrica",
    .toReset           = "Para resetear:",
    .pressEnterTwice   = "Apretar Enter 2 veces",
    .macroMenu         = "Menú macro",
    .forEmergencyUse   = "Sólo Emergencias",
    .pressAnyButton    = "Apretar cualquier botón.",
    .accessibility     = "Accesibilidad",
    .usedHeap          = "Memoria heap usada",
    .broadcast         = "TODOS",
    .radioSettings     = "Ajustes de Radio",
    .offset            = "Offset",
    .macroLatching     = "Macro Latching",
    .noGps             = "Ningún GPS",
    .batteryIcon       = "Icon de batteria",
    .CTCSSTone         = "Tono CTCSS",
    .CTCSSEn           = "CTCSS En.",
    .Encode            = "Codificar",
    .Decode            = "Decodificar",
    .Both              = "Ambos",
    .None              = "Ni",
    .direction         = "Dirección",
    .step              = "Paso",
    .radio             = "Radio",
    .CAN               = "CAN",
    .canRxCheck        = "CAN RX Check",
};
#endif  // SPANISHSTRINGS_H
