// This is a generated file, please do not edit it! Use generate_symbols.py
typedef enum {
    SYMBOL_SPACE = 32,
    SYMBOL_ACCESS_POINT = 33,
    SYMBOL_ALPHA_M_BOX_OUTLINE = 34,
    SYMBOL_ALPHABETICAL_VARIANT = 35,
    SYMBOL_CALL_MADE = 36,
    SYMBOL_CALL_RECEIVED = 37,
    SYMBOL_COG = 38,
    SYMBOL_CROSSHAIRS_GPS = 39,
    SYMBOL_CROSSHAIRS = 40,
    SYMBOL_LOCK = 41,
    SYMBOL_NETWORK = 42,
    SYMBOL_TRANSMISSION_TOWER = 43,
    SYMBOL_WIFI_STRENGTH_1 = 44,
    SYMBOL_WIFI_STRENGTH_2 = 45,
    SYMBOL_WIFI_STRENGTH_3 = 46,
    SYMBOL_WIFI_STRENGTH_4 = 47,
} symbol_t;
