set(OPENRTX_AVAILABLE_TARGETS linux md3x0 mduv3x0 md9600 gd77 dm1801 mod17)
set(OPENRTX_TARGET linux CACHE STRING "Specify the build target")
set_property(CACHE OPENRTX_TARGET PROPERTY STRINGS ${OPENRTX_AVAILABLE_TARGETS})

if(NOT OPENRTX_TARGET IN_LIST OPENRTX_AVAILABLE_TARGETS)
    message(FATAL_ERROR "OPENRTX_TARGET must be one of ${OPENRTX_AVAILABLE_TARGETS}")
endif()

if(NOT OPENRTX_TARGET STREQUAL "linux")
    set(CMAKE_TOOLCHAIN_FILE "cmake/miosix-toolchain.cmake" CACHE STRING "" FORCE)
endif()
