#ifndef DROID_SERVICE_NAMES_H
#define DROID_SERVICE_NAMES_H

// service name: 全局唯一
#define AUDIOFLINGER_SERVICENAME    (123)
#define AUDIOPOLICYSERVICE_SERVICENAME  (234)

#endif // DROID_SERVICE_NAMES_H
