# nothing here
CONFIG_I2C=y
CONFIG_I2C_CSK6=y
CONFIG_ADC=y

CONFIG_UART_CSK6=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y

CONFIG_PWM=y
CONFIG_PWM_CSK6=y

CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_CSK6_LOCK=y

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=90000
CONFIG_HEAP_MEM_POOL_SIZE=81920

CONFIG_CSK_HEAP=y
CONFIG_CSK_HEAP_MEM_POOL_SIZE=307200

CONFIG_CSK6_PSRAM=y

# FROM ESP32S3
CONFIG_POSIX_CLOCK=y
CONFIG_PTHREAD_IPC=y
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP14=y
CONFIG_PRINTK=y
CONFIG_PRINTK_SYNC=y
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_GPIO=y
CONFIG_CLOCK_CONTROL=y
CONFIG_I2C=y
CONFIG_NEWLIB_LIBC=y

# Enable UART logging backend
CONFIG_LOG_BACKEND_UART=y
