name: "Build devcontainer"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'requirements.txt'
      - '.github/workflows/build-devcontainer.yml'
      - '.devcontainer/Dockerfile'
      - '.devcontainer/devcontainer.json'
  pull_request:
    paths:
      - 'requirements.txt'
      - '.github/workflows/build-devcontainer.yml'
      - '.devcontainer/Dockerfile'
      - '.devcontainer/devcontainer.json'

env:
  RADIO_TOOL_VERSION: 0.2.2
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  DEVCONTAINER_NAME: ghcr.io/openrtx/openrtx-devcontainer
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        if: github.repository == 'OpenRTX/OpenRTX' && github.event_name != 'pull_request'
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
            imageName: ${{ env.DEVCONTAINER_NAME }}
            cacheFrom: ${{ env.DEVCONTAINER_NAME }}
            push: ${{ github.repository == 'OpenRTX/OpenRTX' && github.event_name != 'pull_request' && 'always' || 'never' }}
