name: Build docker container and push it to Github
on:
  pull_request:
  push:

env:
  REGISTRY_IMAGE: ghcr.io/peterus/openrtx

jobs:
  build:
    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#      attestations: write
#      id-token: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v5

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and release devcontainer Multi-Platform
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.REGISTRY_IMAGE }}
          cacheFrom: ${{ env.REGISTRY_IMAGE }}
          platform: linux/amd64,linux/arm64
          push: always
