name: "Check if symbols need to be regenerated"
on:
  workflow_dispatch:
  push:
    paths:
    - 'openrtx/include/fonts/symbols/**/*'
  pull_request:
    paths:
      - 'openrtx/include/fonts/symbols/**/*'


jobs:
  check-symbol-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install-deps
        run: |
          sudo apt update
          sudo apt install ffmpeg clang-format
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        run: uv python install
      - name: Setup script dependencies
        run: uv sync --locked
      - name: Run symbols script and then format the output
        run: |
          uv run ./scripts/generate_symbols.py
          uv run ./scripts/clang_format.sh
      - name: Fail the build if there are changes generated
        run: |
          git --no-pager diff
          git diff-index --quiet HEAD
